version: '3.9'

services:
  frontend:
    image: 'kimchi06/recipe-management-system-frontend:v1.0'
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    command: npm start

  server:
    image: 'kimchi06/recipe-management-system-server:v1.0'
    ports: 
      - "8081:8080"
    depends_on:
      - db

  db:
    image: 'postgres'
    ports:
      - '4444:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'root'